PROGRAMS = [
    {
        "program_id": "urge-reset-14",
        "title": "14-Day Urge Reset",
        "description": "Understand your urges and build control in 2 weeks",
        "duration_days": 14,
        "category": "beginner",
        "icon": "zap",
        "days": [
            {"day": 1, "title": "Know Your Enemy", "insight": "Urges are not commands. They are signals from your brain, triggered by habit loops. Understanding this is the first step to control.", "action": "Write down your top 3 triggers. Keep this list visible.", "reflection": "When did you last feel an urge? What were you doing?"},
            {"day": 2, "title": "The 90-Second Rule", "insight": "Most urges peak and pass within 90 seconds. Your brain is testing you, not commanding you.", "action": "Next time you feel an urge, set a 90-second timer and just breathe.", "reflection": "Did the urge feel different when you timed it?"},
            {"day": 3, "title": "Delay the Urge", "insight": "Urges peak and pass. The longer you delay, the weaker they get. Every minute counts.", "action": "Use the 10-min timer once today when you feel an urge.", "reflection": "What triggered your urge today?"},
            {"day": 4, "title": "Your Trigger Map", "insight": "Triggers follow patterns: time, place, emotion, people. Map yours to predict and prevent.", "action": "Log every urge today with its trigger in the app.", "reflection": "Do you see any patterns forming?"},
            {"day": 5, "title": "The Power of Environment", "insight": "Your environment shapes 80% of your behavior. Change the environment, change the habit.", "action": "Remove or hide one thing that triggers you.", "reflection": "How does your space influence your behavior?"},
            {"day": 6, "title": "Breathe Through It", "insight": "Deep breathing activates your parasympathetic nervous system, calming the urge response.", "action": "Do the 4-4-6 breathing exercise (inhale 4s, hold 4s, exhale 6s) three times today.", "reflection": "How did breathing change how the urge felt?"},
            {"day": 7, "title": "Week 1 Check-in", "insight": "You made it 7 days. That is not luck, it is proof of your strength. Celebrate small wins.", "action": "Write yourself a message about why you started this journey.", "reflection": "What is the biggest thing you have learned this week?"},
            {"day": 8, "title": "Identity Shift", "insight": "You are not someone trying to quit. You are someone who does not do that anymore. Identity drives behavior.", "action": "Say out loud: I am someone who controls my urges.", "reflection": "How does it feel to say that?"},
            {"day": 9, "title": "The Replacement Strategy", "insight": "You cannot just remove a habit. You need to replace it with something better.", "action": "Choose one healthy replacement activity for your main trigger.", "reflection": "What activity could fill the gap?"},
            {"day": 10, "title": "Emotional Awareness", "insight": "Most relapses happen when we are tired, lonely, angry, or hungry (HALT). Check in with yourself.", "action": "Do a HALT check 3 times today: Am I Hungry, Angry, Lonely, or Tired?", "reflection": "Which of the HALT states affects you most?"},
            {"day": 11, "title": "The Urge Surfing Technique", "insight": "Instead of fighting urges, observe them like waves. They rise, peak, and fall. You just need to surf.", "action": "When an urge comes, narrate it: The urge is rising... it is peaking... it is fading.", "reflection": "Did observing the urge change your relationship with it?"},
            {"day": 12, "title": "Build Your Support System", "insight": "Recovery is not a solo journey. Having even one person who understands makes a huge difference.", "action": "Tell one person about your journey, or add a buddy in the app.", "reflection": "Who in your life supports your growth?"},
            {"day": 13, "title": "Forgiveness Practice", "insight": "Shame fuels relapse. Self-compassion fuels recovery. Be kind to yourself.", "action": "Write a forgiveness letter to yourself. You do not need to be perfect.", "reflection": "What would you tell a friend in your situation?"},
            {"day": 14, "title": "Your New Foundation", "insight": "14 days of learning. You now have tools, awareness, and proof that you can do this.", "action": "Review your trigger log and write down your 3 biggest insights.", "reflection": "How are you different from 14 days ago?"},
        ]
    },
    {
        "program_id": "break-habit-30",
        "title": "30 Days to Break the Habit",
        "description": "A deep behavior change program to rewire your patterns",
        "duration_days": 30,
        "category": "intermediate",
        "icon": "flame",
        "days": [
            {"day": 1, "title": "Commitment Day", "insight": "Today you draw a line. Not because you are weak, but because you are choosing strength.", "action": "Write your commitment statement: I am choosing to change because...", "reflection": "What does freedom from this habit look like?"},
            {"day": 2, "title": "The Habit Loop", "insight": "Every habit follows: Cue > Routine > Reward. To break the habit, you must disrupt the loop.", "action": "Identify the cue, routine, and reward for your habit.", "reflection": "What reward is your habit actually giving you?"},
            {"day": 3, "title": "Your Why", "insight": "Motivation fades. Purpose does not. Your why is what carries you through the hard days.", "action": "Write 3 reasons why you want to change. Save them in the app.", "reflection": "Which reason hits you the hardest?"},
            {"day": 4, "title": "Trigger Audit", "insight": "You cannot avoid what you do not see. Today we map every trigger.", "action": "Log every urge today with time, location, emotion, and trigger.", "reflection": "Were there any surprises in your trigger log?"},
            {"day": 5, "title": "The First Replacement", "insight": "Nature hates a vacuum. Remove a bad habit without replacing it and it will come back.", "action": "Choose your first replacement habit. Start it today.", "reflection": "How did the replacement feel compared to the old habit?"},
            {"day": 6, "title": "Morning Routine Power", "insight": "How you start the day sets the tone. A strong morning reduces vulnerability all day.", "action": "Set a simple 3-step morning routine and follow it tomorrow.", "reflection": "Do you currently have a morning routine?"},
            {"day": 7, "title": "Week 1 Reflection", "insight": "One week down. You have already proven something to yourself.", "action": "Review this week. What worked? What was hard?", "reflection": "Rate your week 1-10 and explain why."},
            {"day": 8, "title": "Stress Management", "insight": "Stress is the number one relapse trigger. Managing stress is managing recovery.", "action": "Try one stress relief technique: walk, breathing, or journaling.", "reflection": "What is your go-to stress response? Is it healthy?"},
            {"day": 9, "title": "The Boredom Trap", "insight": "Boredom is a trigger because your brain seeks stimulation. Give it better options.", "action": "Create a list of 5 things you can do when bored instead.", "reflection": "When are you most bored during the day?"},
            {"day": 10, "title": "Social Triggers", "insight": "People and places carry associations. Some environments make relapse almost automatic.", "action": "Identify one social trigger and plan how to handle it.", "reflection": "Are there people who make it harder for you?"},
            {"day": 11, "title": "The Evening Protocol", "insight": "Evenings are high-risk. A structured wind-down routine is your shield.", "action": "Create a 30-min evening routine. No screens, calm activities.", "reflection": "What do your evenings currently look like?"},
            {"day": 12, "title": "Gratitude as Medicine", "insight": "Gratitude rewires your brain toward positive patterns. It is a natural antidote to craving.", "action": "Write 3 things you are grateful for today.", "reflection": "How does gratitude change your mood?"},
            {"day": 13, "title": "Physical Movement", "insight": "Exercise releases the same feel-good chemicals your habit does, but sustainably.", "action": "Move your body for 15 minutes today. Walk, stretch, anything.", "reflection": "How did you feel after moving?"},
            {"day": 14, "title": "Halfway Point", "insight": "14 days. You are building something real. This is not just willpower, it is rewiring.", "action": "Compare how you feel now vs day 1.", "reflection": "What has changed the most?"},
            {"day": 15, "title": "Identity Deepening", "insight": "Every action is a vote for the person you want to become. You are casting votes daily.", "action": "Describe the person you are becoming in 3 sentences.", "reflection": "Do your daily actions match that identity?"},
            {"day": 16, "title": "Dealing with Cravings", "insight": "Cravings are like clouds. They come, they cover the sky, and then they pass.", "action": "Practice urge surfing: observe the craving without acting for 10 minutes.", "reflection": "What did you notice about the craving as you watched it?"},
            {"day": 17, "title": "Sleep Optimization", "insight": "Poor sleep increases impulsivity by 60%. Sleep is your secret weapon.", "action": "Set a consistent bedtime and wake time for the next 2 weeks.", "reflection": "How many hours do you typically sleep?"},
            {"day": 18, "title": "Nutrition Connection", "insight": "Blood sugar crashes trigger cravings. Stable energy means stable willpower.", "action": "Eat 3 balanced meals today. No skipping.", "reflection": "Do you notice a connection between hunger and urges?"},
            {"day": 19, "title": "Accountability Check", "insight": "Sharing your journey with someone multiplies your commitment.", "action": "Update your buddy or journal about your progress.", "reflection": "Who holds you accountable?"},
            {"day": 20, "title": "Handling Setbacks", "insight": "A slip is not a fall. It is a stumble. What matters is the next step, not the last one.", "action": "Write a pre-planned response for if you slip.", "reflection": "Can you forgive yourself for past slips?"},
            {"day": 21, "title": "3 Week Milestone", "insight": "21 days. Research shows this is when new neural pathways start to solidify.", "action": "Celebrate this milestone. You deserve it.", "reflection": "What are you most proud of?"},
            {"day": 22, "title": "Deeper Triggers", "insight": "Surface triggers hide deeper needs: connection, comfort, escape, control.", "action": "For your main trigger, ask why 5 times to find the root.", "reflection": "What is the deeper need behind your habit?"},
            {"day": 23, "title": "Building Resilience", "insight": "Resilience is not about never falling. It is about getting up faster each time.", "action": "Recall a time you overcame something hard. Draw strength from it.", "reflection": "What makes you resilient?"},
            {"day": 24, "title": "Future Visualization", "insight": "Your brain cannot distinguish vividly imagined futures from memories. Use this.", "action": "Spend 5 minutes visualizing your life free from this habit.", "reflection": "What does your best future look like?"},
            {"day": 25, "title": "Habit Stacking", "insight": "Attach new habits to existing ones. After I do X, I will do Y.", "action": "Create 2 habit stacks for your daily routine.", "reflection": "Which existing habits can anchor new ones?"},
            {"day": 26, "title": "Managing Energy", "insight": "Willpower depletes. Schedule important decisions when energy is high.", "action": "Map your energy levels through the day. Plan accordingly.", "reflection": "When are you at your strongest and weakest?"},
            {"day": 27, "title": "Connection Over Perfection", "insight": "Loneliness is a top trigger. Connection is the opposite of addiction.", "action": "Reach out to someone today. A call, a text, a visit.", "reflection": "Do you feel connected to others?"},
            {"day": 28, "title": "Your Toolbox Review", "insight": "You now have dozens of tools. Not all will work every time. That is okay.", "action": "List your top 5 most effective tools from this program.", "reflection": "Which tool surprised you the most?"},
            {"day": 29, "title": "Letter to Future Self", "insight": "Write to the future you who might struggle. Your words today can save tomorrow.", "action": "Write a letter to your future self for hard days.", "reflection": "What would you want to hear when things get tough?"},
            {"day": 30, "title": "Graduation Day", "insight": "30 days of intentional change. You are not the same person who started. Keep going.", "action": "Review your entire journey. Save your top insights.", "reflection": "Who are you now?"},
        ]
    },
    {
        "program_id": "trigger-mastery",
        "title": "Trigger Mastery",
        "description": "Identify, understand, and master your trigger patterns",
        "duration_days": 14,
        "category": "intermediate",
        "icon": "target",
        "days": [
            {"day": 1, "title": "What is a Trigger?", "insight": "A trigger is anything that activates the craving response: a place, person, time, emotion, or thought.", "action": "List 5 situations where you typically feel urges.", "reflection": "Which trigger feels the most powerful?"},
            {"day": 2, "title": "External vs Internal", "insight": "External triggers are places and people. Internal triggers are emotions and thoughts. Both are manageable.", "action": "Sort your triggers into external and internal categories.", "reflection": "Which type affects you more?"},
            {"day": 3, "title": "The Trigger Timeline", "insight": "Triggers follow your daily schedule. The same times create the same urges.", "action": "Track what time urges hit today. Log every one.", "reflection": "Do you see a time pattern?"},
            {"day": 4, "title": "Emotional Triggers Deep Dive", "insight": "Stress, loneliness, boredom, anger and anxiety are the top 5 emotional triggers.", "action": "Rate each of these 1-10 for how much they trigger you.", "reflection": "Which emotion is your biggest vulnerability?"},
            {"day": 5, "title": "Location Triggers", "insight": "Your brain links places to behaviors. Some locations are automatic trigger zones.", "action": "Identify your top 3 trigger locations and plan alternatives.", "reflection": "Can you avoid or change these locations?"},
            {"day": 6, "title": "Social Triggers", "insight": "Certain people or social situations can trigger urges without you even realizing it.", "action": "Identify people or situations that increase your urges.", "reflection": "How can you set boundaries?"},
            {"day": 7, "title": "Week 1 Pattern Review", "insight": "After a week of tracking, patterns emerge. Data is power.", "action": "Review your urge log. What are your top 3 patterns?", "reflection": "Did anything surprise you?"},
            {"day": 8, "title": "Avoidance Strategy", "insight": "The easiest trigger to beat is the one you never face. Avoidance is not weakness, it is strategy.", "action": "Remove or avoid one trigger source today.", "reflection": "What can you remove from your environment?"},
            {"day": 9, "title": "Coping Strategy", "insight": "For triggers you cannot avoid, you need a coping plan ready before the trigger hits.", "action": "Create an if-then plan: If I feel [trigger], then I will [action].", "reflection": "Do you have enough coping tools?"},
            {"day": 10, "title": "The Stress-Urge Connection", "insight": "Stress makes you 5x more likely to relapse. Managing stress is managing triggers.", "action": "Practice one stress management technique for 10 minutes.", "reflection": "How does your body feel when stressed?"},
            {"day": 11, "title": "Reframing Triggers", "insight": "A trigger is not a threat. It is information. It tells you what your brain needs.", "action": "Next urge, ask: what do I actually need right now?", "reflection": "What need is hiding behind the trigger?"},
            {"day": 12, "title": "Building Trigger Resistance", "insight": "Each time you face a trigger and do not give in, you get stronger. It is training.", "action": "Intentionally expose yourself to a mild trigger and resist.", "reflection": "How did it feel to resist intentionally?"},
            {"day": 13, "title": "Your Trigger Playbook", "insight": "The best defense is a prepared one. A trigger playbook is your battle plan.", "action": "Write a response plan for your top 5 triggers.", "reflection": "Do you feel more prepared now?"},
            {"day": 14, "title": "Trigger Master", "insight": "You now understand your triggers better than ever. Knowledge is your armor.", "action": "Summarize your biggest trigger insights. Save them.", "reflection": "How has your relationship with triggers changed?"},
        ]
    },
    {
        "program_id": "night-control",
        "title": "Night Control Program",
        "description": "For those who struggle most at night. Build an evening shield.",
        "duration_days": 7,
        "category": "focused",
        "icon": "moon",
        "days": [
            {"day": 1, "title": "Why Nights Are Hard", "insight": "At night, willpower is depleted, you are tired, alone, and bored. It is the perfect storm for relapse.", "action": "Track what time your urges hit tonight. Log the emotion.", "reflection": "What makes nighttime particularly hard for you?"},
            {"day": 2, "title": "The Screen Problem", "insight": "Screens stimulate your brain and can lead to trigger content. A digital boundary is essential.", "action": "Set a no-phone rule starting 1 hour before bed tonight.", "reflection": "What do you typically do on your phone at night?"},
            {"day": 3, "title": "Build Your Evening Ritual", "insight": "A structured evening removes the decision space where urges thrive.", "action": "Create a 30-min wind-down routine: tea, reading, stretching, journaling.", "reflection": "What calming activities do you enjoy?"},
            {"day": 4, "title": "The Bedroom Reset", "insight": "Your environment should signal safety, not temptation. Redesign your space.", "action": "Remove one trigger item from your bedroom. Add one calming item.", "reflection": "Does your bedroom feel like a safe space?"},
            {"day": 5, "title": "Loneliness After Dark", "insight": "Night loneliness amplifies urges. Having a plan for connection matters.", "action": "Identify one person you can text or call if struggling at night.", "reflection": "Do you feel more alone at night?"},
            {"day": 6, "title": "The Emergency Protocol", "insight": "When the urge is strong at night, you need a fast action plan. No thinking, just doing.", "action": "Write your nighttime emergency plan: step 1, step 2, step 3.", "reflection": "Do you feel more prepared for tonight?"},
            {"day": 7, "title": "Night Control Achieved", "insight": "You now have tools, routines, and a plan for nighttime. Use them every night.", "action": "Follow your full evening routine tonight.", "reflection": "How do your nights feel different now?"},
        ]
    },
]

PRESET_URGE_TYPES = [
    {"id": "smoking", "label": "Smoking", "icon": "cigarette"},
    {"id": "drinking", "label": "Drinking", "icon": "wine"},
    {"id": "gambling", "label": "Gambling", "icon": "dice"},
    {"id": "drugs", "label": "Drugs", "icon": "pill"},
    {"id": "overeating", "label": "Overeating", "icon": "utensils"},
    {"id": "social_media", "label": "Social Media", "icon": "smartphone"},
    {"id": "shopping", "label": "Shopping", "icon": "shopping-bag"},
    {"id": "pornography", "label": "Pornography", "icon": "eye-off"},
    {"id": "gaming", "label": "Gaming", "icon": "gamepad-2"},
    {"id": "other", "label": "Other", "icon": "plus-circle"},
]

PRESET_HABITS = [
    {"habit_id": "drink-water", "name": "Drink water", "icon": "droplets", "category": "health"},
    {"habit_id": "go-walk", "name": "Go for a walk", "icon": "footprints", "category": "exercise"},
    {"habit_id": "journal", "name": "Journal", "icon": "book-open", "category": "mindfulness"},
    {"habit_id": "meditate", "name": "Meditation", "icon": "brain", "category": "mindfulness"},
    {"habit_id": "call-friend", "name": "Call a friend", "icon": "phone", "category": "connection"},
    {"habit_id": "breathing", "name": "Breathing exercise", "icon": "wind", "category": "mindfulness"},
    {"habit_id": "no-phone-bed", "name": "No phone before bed", "icon": "smartphone-off", "category": "evening"},
    {"habit_id": "evening-routine", "name": "Evening routine", "icon": "moon", "category": "evening"},
    {"habit_id": "exercise", "name": "Exercise 15 min", "icon": "dumbbell", "category": "exercise"},
    {"habit_id": "gratitude", "name": "Write 3 gratitudes", "icon": "heart", "category": "mindfulness"},
]
